using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace JTex.Forms.ArTMS
{
    public partial class PPOverViewAll : Form
    {
        public PPOverViewAll()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        Modelx.ATMSEntityModel DbContext = new Modelx.ATMSEntityModel();

        public static bool FindSomething = false;
        Modelx.ATMSEntityModel DbxContext = new Modelx.ATMSEntityModel();
        public event EventHandler ButtonFirstFormClicked;
        private void PPOverViewAll_Load(object sender, EventArgs e)
        {
            //GetArticleID();
            //MessageBox.Show(""+FindSomething);
            FindSomething = true;

            MainForm mf = new MainForm();
            //mf.NB_PO_DEFINE_LinkClicked(sender,e);
        }
        private void ViewALL()
        {
            
               
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
        }

        private void bbiPrintPreview_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridControl1.ShowRibbonPrintPreview();
        }
        public int GetArticleID()
        {
            int articleID;
            using (var db = new Modelx.ATMSEntityModel())
            {
                articleID = db.Articles.Where(u => u.StyleNumber == "TLCN135BLK").Select(u => u.ArticleID).SingleOrDefault();         
            }
            return articleID;
        }
        //ArticlesForm bf;
        private void gridControl1_KeyDown(object sender, KeyEventArgs e)
        {
            //if (e.KeyCode == Keys.Enter)
            //{
            //    MessageBox.Show("In Function"+FindSomething);

            //    if (bf == null)
            //    {
            //        bf = new ArticlesForm();
            //        bf.Show();
            //        bf.BringToFront();
            //        bf.FormClosed += Bf_FormClosed;
            //    }
            //    else if (bf != null)
            //    {
            //        bf.BringToFront();
            //    }
            //    else
            //    {
            //        bf.Activate();
            //    }
            //}
        }

        private void Bf_FormClosed(object sender, FormClosedEventArgs e)
        {
            //bf = null;
        }
    }
}
