using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace JTex.Forms.Inventory.Yarn
{
    public partial class YarnStockEnteryForm : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public YarnStockEnteryForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            IMS.IMSEntityModel dbContext = new IMS.IMSEntityModel();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.YarnStocks.Load();
            // This line of code is generated by Data Source Configuration Wizard
            yarnStocksBindingSource.DataSource = dbContext.YarnStocks.Local.ToBindingList();
        }
    }
}
