using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Modelx;

namespace JTex.Forms.ArTMS
{
    public partial class ColorsForm : Form
    {
        public ColorsForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Modelx.ATMSEntityModel dbContext = new Modelx.ATMSEntityModel();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Colors.Load();
            // This line of code is generated by Data Source Configuration Wizard
            colorsBindingSource.DataSource = dbContext.Colors.Local.ToBindingList();
        }
        ATMSEntityModel atmObj = new ATMSEntityModel();
        Modelx.Color cObj = new Modelx.Color();

        private void popGrid()
        {
            atmObj = new ATMSEntityModel();
            atmObj.Colors.Load();
            gridControl1.DataSource = atmObj.Colors.Local;
        }
        private void bbiNew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            cObj.Name = NameTextEdit.Text.Trim();
            cObj.Description = DescriptionTextEdit.Text.Trim();
            cObj.isActive = isActiveCheckEdit.Checked;

            using (var myDbEntities = new ATMSEntityModel())
            {
                myDbEntities.Colors.Add(cObj);
                myDbEntities.SaveChanges();
            }
            popGrid();
        }

        private void bbiPrintPreview_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridControl1.ShowRibbonPrintPreview();
        }

        private void bbiEdit_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (ColorIDTextEdit.Text != "")
            {
                cObj.ColorID = Convert.ToByte(ColorIDTextEdit.Text.Trim());
                cObj.Name = NameTextEdit.Text.Trim();
                cObj.Description = DescriptionTextEdit.Text.Trim();
                cObj.isActive = isActiveCheckEdit.Checked;

                using (var dbEntities = new ATMSEntityModel())
                {
                    dbEntities.Entry(cObj).State = EntityState.Modified;
                    dbEntities.SaveChanges();
                }
                popGrid();
            }
            else
            {
                MessageBox.Show("Please enter color id...");
            }
        }

        private void ColorsForm_Load(object sender, EventArgs e)
        {

        }

        private void bbiDelete_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (ColorIDTextEdit.Text != "")
            {
                cObj.ColorID = Convert.ToByte(ColorIDTextEdit.Text.Trim());

                using (var dbEntities = new ATMSEntityModel())
                {
                    dbEntities.Colors.Attach(cObj);
                    dbEntities.Colors.Remove(cObj);
                    dbEntities.SaveChanges();
                }
                popGrid();
            }
            else
            {
                MessageBox.Show("Please enter color id...");
            }
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            try
            {
                ColorIDTextEdit.Text = gridView1.GetFocusedRowCellValue("ColorID").ToString().Trim();
                NameTextEdit.Text = gridView1.GetFocusedRowCellValue("Name").ToString().Trim();
                DescriptionTextEdit.Text = gridView1.GetFocusedRowCellValue("Description").ToString().Trim();
                isActiveCheckEdit.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("isActive"));
            }
            catch(Exception ex)
            {

            }
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
        }
    }
}
