using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Microsoft.Office.Interop.Excel;
using Excel = Microsoft.Office.Interop.Excel;

namespace JTex.Forms.ArTMS
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Modelx.ATMSEntityModel dbContext = new Modelx.ATMSEntityModel();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Brands.Load();
            // This line of code is generated by Data Source Configuration Wizard
            brandsBindingSource.DataSource = dbContext.Brands.Local.ToBindingList();
        }

        private void bunifuFlatButton1_MouseHover(object sender, EventArgs e)
        {
           
        }

        private void bunifuFlatButton1_MouseLeave(object sender, EventArgs e)
        {
           
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            System.Diagnostics.Process.Start(@"C:\Users\fahid\OneDrive\Desktop\Desktop\invoice.xls");
        }

        private void bunifuFlatButton1_Click(object sender, EventArgs e)
        {
            
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            MessageBox.Show(""+ lookUpEdit1.EditValue);
        }
    }
}
