using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Modelx;

namespace JTex.Forms.ArTMS
{
    public partial class SeasonForm : Form
    {
        public SeasonForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Modelx.ATMSEntityModel dbContext = new Modelx.ATMSEntityModel();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Seasons.Load();
            // This line of code is generated by Data Source Configuration Wizard
            seasonsBindingSource.DataSource = dbContext.Seasons.Local.ToBindingList();
        }
        ATMSEntityModel atmObj = new ATMSEntityModel();
        Modelx.Season sObj = new Modelx.Season();

        private void popGrid()
        {
            atmObj = new ATMSEntityModel();
            atmObj.Seasons.Load();
            gridControl1.DataSource = atmObj.Seasons.Local;
        }
        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
        }

        private void bbiPrintPreview_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridControl1.ShowRibbonPrintPreview();
        }

        private void SeasonForm_Load(object sender, EventArgs e)
        {

        }

        private void bbiNew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            sObj.Name = NameTextEdit.Text.Trim();
            sObj.Description = DescriptionTextEdit.Text.Trim();
            sObj.isActive = isActiveCheckEdit.Checked;

            using (var myDbEntities = new ATMSEntityModel())
            {
                myDbEntities.Seasons.Add(sObj);
                myDbEntities.SaveChanges();
            }
            popGrid();
        }

        private void bbiEdit_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (SeasonIDTextEdit.Text != "")
            {
                sObj.SeasonID = Convert.ToByte(SeasonIDTextEdit.Text.Trim());
                sObj.Name = NameTextEdit.Text.Trim();
                sObj.Description = DescriptionTextEdit.Text.Trim();
                sObj.isActive = isActiveCheckEdit.Checked;

                using (var myDbEntities = new ATMSEntityModel())
                {
                    myDbEntities.Entry(sObj).State = EntityState.Modified;
                    myDbEntities.SaveChanges();
                }
                popGrid();
            }
            else
            {
                MessageBox.Show("Please insert season id....");
            }
        }

        private void bbiDelete_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (SeasonIDTextEdit.Text != "")
            {
                sObj.SeasonID = Convert.ToByte(SeasonIDTextEdit.Text.Trim());
                using (var myDbEntities = new ATMSEntityModel())
                {
                    myDbEntities.Entry(sObj).State = EntityState.Deleted;
                    myDbEntities.SaveChanges();
                }
                popGrid();
            }
            else
            {
                MessageBox.Show("Please insert season id....");
            }
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            try
            {
                SeasonIDTextEdit.Text = gridView1.GetFocusedRowCellValue("SeasonID").ToString().Trim();
                NameTextEdit.Text= gridView1.GetFocusedRowCellValue("Name").ToString().Trim();
                DescriptionTextEdit.Text= gridView1.GetFocusedRowCellValue("Description").ToString().Trim();
                isActiveCheckEdit.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("isActive"));
            }
            catch(Exception ex)
            {

            }
        }
    }
    }

