using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace JTex.Forms.HR
{
    public partial class EmployeeForm : Form
    {
        public EmployeeForm()
        {
            InitializeComponent();

            //departmentTableAdapter1.Fill(departmentDataSet1.Department);
            //// This line of code is generated by Data Source Configuration Wizard
            //sectionTableAdapter1.Fill(sectionDataSet1.Section);
            //// This line of code is generated by Data Source Configuration Wizard
            //subsectionTableAdapter1.Fill(subsectionDataSet1.Subsection);
            //// This line of code is generated by Data Source Configuration Wizard
            //shiftsTableAdapter1.Fill(shiftsDataSet1.Shifts);
            //// This line of code is generated by Data Source Configuration Wizard
            //designationTableAdapter1.Fill(designationDataSet1.Designation);
        }

        private void EmployeeForm_Load(object sender, EventArgs e)
        {
            //this.employeeTableAdapter.Fill(this.employeeDataSet.Employee);
            //DevExpress.XtraEditors.XtraMessageBox.Show("Okkkk?", "Open", MessageBoxButtons.YesNo, MessageBoxIcon.Asterisk);

        }

        private void pictureEdit1_MouseDoubleClick_1(object sender, MouseEventArgs e)
        {
            OpenFileDialog open = new OpenFileDialog();
            open.Filter = "(*.jpg; *.jpeg; *.png; *.gif;)|*.jpg; *.jpeg; *.png; *.gif;";
            if (open.ShowDialog() == DialogResult.OK)
            {
                pictureEdit1.Image = Image.FromFile(open.FileName);
            }
        }

        private void departmentBindingSource_CurrentChanged(object sender, EventArgs e)
        {

        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            
            try
            {
                if (gridView1.GetFocusedRowCellValue("PicturePath") != System.DBNull.Value)
                {
                    pictureEdit1.Image = Image.FromFile(gridView1.GetFocusedRowCellValue("PicturePath").ToString());
                    EmployeeSequenceIDTextEdit.Text = gridView1.GetFocusedRowCellValue("EmployeeSequenceID").ToString().Trim();
                    DepartmentIDTextEdit.Text = gridView1.GetFocusedRowCellValue("DepartmentID").ToString().Trim();
                    SectionIDTextEdit.Text = gridView1.GetFocusedRowCellValue("SectionID").ToString().Trim();
                    SubsectionIDTextEdit.Text = gridView1.GetFocusedRowCellValue("SubsectionID").ToString().Trim();
                    DesignationIDTextEdit.Text = gridView1.GetFocusedRowCellValue("DesignationID").ToString().Trim();
                    dateDateEdit.Text = gridView1.GetFocusedRowCellValue("date").ToString().Trim();
                    NameTextEdit.Text = gridView1.GetFocusedRowCellValue("Name").ToString().Trim();
                    PicturePathTextEdit.Text = gridView1.GetFocusedRowCellValue("PicturePath").ToString().Trim();
                    AddressTextEdit.Text = gridView1.GetFocusedRowCellValue("Address").ToString().Trim();
                    FatherNameTextEdit.Text = gridView1.GetFocusedRowCellValue("FatherName").ToString().Trim();
                    FatherProfessionTextEdit.Text = gridView1.GetFocusedRowCellValue("FatherProfession").ToString().Trim();
                    CNICTextEdit.Text = gridView1.GetFocusedRowCellValue("CNIC").ToString().Trim();
                    ContactNumberTextEdit.Text = gridView1.GetFocusedRowCellValue("ContactNumber").ToString().Trim();
                    BloodGroupTextEdit.Text = gridView1.GetFocusedRowCellValue("BloodGroup").ToString().Trim();
                    MartialStatusTextEdit.Text = gridView1.GetFocusedRowCellValue("MartialStatus").ToString().Trim();
                    EmailTextEdit.Text = gridView1.GetFocusedRowCellValue("Email").ToString().Trim();
                    DOBDateEdit.Text = gridView1.GetFocusedRowCellValue("DOB").ToString().Trim();
                    QualificationTextEdit.Text = gridView1.GetFocusedRowCellValue("Qualification").ToString().Trim();
                    WHNameTextEdit.Text = gridView1.GetFocusedRowCellValue("WHName").ToString().Trim();
                    CNIC2TextEdit.Text = gridView1.GetFocusedRowCellValue("CNIC2").ToString().Trim();
                    EmergencyContactNumberTextEdit.Text = gridView1.GetFocusedRowCellValue("EmergencyContactNumber").ToString().Trim();
                    EmployeeLevelTextEdit.Text = gridView1.GetFocusedRowCellValue("EmployeeLevel").ToString().Trim();
                    FileStatusTextEdit.Text = gridView1.GetFocusedRowCellValue("FileStatus").ToString().Trim();
                    JobStatusTextEdit.Text = gridView1.GetFocusedRowCellValue("JobStatus").ToString().Trim();
                    ExperianceTextEdit.Text = gridView1.GetFocusedRowCellValue("Experiance").ToString().Trim();
                    TBSalary.Text = gridView1.GetFocusedRowCellValue("Salary").ToString().Trim();
                    TBConveyance.Text = gridView1.GetFocusedRowCellValue("Conveince").ToString().Trim();
                    TBAdditional.Text = gridView1.GetFocusedRowCellValue("Additional").ToString().Trim();
                    TBBarcode.Text = gridView1.GetFocusedRowCellValue("Barcode").ToString().Trim();
                    //OverTimeEntitledCheckEdit.Text = gridView1.GetFocusedRowCellValue("OvertimeEntitled").ToString().Trim();
                    ProbationCheckEdit.Text = gridView1.GetFocusedRowCellValue("Probation").ToString().Trim();
                    //MessageBox.Show(gridView1.GetFocusedRowCellValue("Probation").ToString().Trim());
                }
            }
            catch(Exception ex)
            {

            }
        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
            string fName = 1.ToString() + ".jpg";
            string folder = @"F:\Employee Pictures2";
            string PathString = System.IO.Path.Combine(folder, fName);
            Image a = pictureEdit1.Image;
            a.Save(PathString);
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
            string fName= 1.ToString() + ".jpg";
            string folder = @"F:\Employee Pictures2";
            string PathString = System.IO.Path.Combine(folder, fName);
            if (System.IO.File.Exists(PathString))
            {
                MessageBox.Show("Existed");
                System.IO.File.Delete(PathString);
            }
            else
            {
                MessageBox.Show("Don't Exist");
            }
        }

        private void pictureEdit1_EditValueChanged(object sender, EventArgs e)
        {

        }
        
        

    }
}
