using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;


namespace JTex.Forms.HR
{
    public partial class LoanForm : Form
    {
        public LoanForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
        }

        private void ClearAll()
        {
            l_idTextEdit.Text = "";
            EmployeeIDTextEdit.Text = "";
            AmountTextEdit.Text = "";
            PartitionsTextEdit.Text = "";
            issueDateDateEdit.Text = "";
            RemainingAmountTextEdit.Text = "";
            ClearCheckEdit.EditValue = false;
        }

        private void LoanSelection()
        {
           
        }
        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {

        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
           
        }

        private void BtnUpdate_Click(object sender, EventArgs e)
        {
            
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
            
        }

        private void BtnClear_Click(object sender, EventArgs e)
        {
            ClearAll();
        }
    }
}
