using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Modelx;


namespace JTex.Forms.HR
{
    public partial class ShiftForm : Form
    {
        public ShiftForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Modelx.ADOEntityModel dbContext = new Modelx.ADOEntityModel();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Shifts.Load();
            // This line of code is generated by Data Source Configuration Wizard
            shiftsBindingSource.DataSource = dbContext.Shifts.Local.ToBindingList();
        }
        ADOEntityModel DbContext = new ADOEntityModel();
        Shift sObj = new Shift();


        private void ShiftForm_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'shiftsDataSet.Shifts' table. You can move, or remove it, as needed.

        }

        private void  popGrid()
        {
            DbContext = new ADOEntityModel();
            DbContext.Shifts.Load();
            gridControl1.DataSource = DbContext.Shifts.Local;
        }


        private void bbiPrintPreview_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridControl1.ShowRibbonPrintPreview();
        }

        private void bbiNew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            sObj.Name = NameTextEdit.Text.Trim();
            sObj.Number = Convert.ToInt32(NumberTextEdit.Text.Trim());
            sObj.StartTime = StartTimeTimeSpanEdit.Time.TimeOfDay;

            using (var DbEntities = new ADOEntityModel())
            {
                DbEntities.Shifts.Add(sObj);
                DbEntities.SaveChanges();
            }
            popGrid();
        }

        private void bbiEdit_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if(ShiftIDTextEdit.Text!="")
            {
                sObj.ShiftID = Convert.ToInt32(ShiftIDTextEdit.Text.Trim());
                sObj.Name = NameTextEdit.Text.Trim();
                sObj.Number = Convert.ToInt32(NumberTextEdit.Text.Trim());
                sObj.StartTime = StartTimeTimeSpanEdit.Time.TimeOfDay;

                using (var DbEntities = new ADOEntityModel())
                {
                    DbEntities.Entry(sObj).State = EntityState.Modified;
                    DbEntities.SaveChanges();
                }
                popGrid();
            }
            else
            {
                MessageBox.Show("Please enter shift id...");
            }
        }

        private void bbiDelete_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (ShiftIDTextEdit.Text != "")
            {
                sObj.ShiftID = Convert.ToInt32(ShiftIDTextEdit.Text.Trim());
                using (var myDbEntities = new ADOEntityModel())
                {
                    var entery = myDbEntities.Entry(sObj);
                    if (entery.State == System.Data.Entity.EntityState.Detached)
                    {
                        myDbEntities.Shifts.Attach(sObj);
                        myDbEntities.Shifts.Remove(sObj);
                        myDbEntities.SaveChanges();
                    }
                }
                popGrid();
            }        
            else
            {
                MessageBox.Show("Please enter shift id...");
            }
        }

        private void gridView1_FocusedRowChanged_1(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            try
            {
                ShiftIDTextEdit.Text = gridView1.GetFocusedRowCellValue("ShiftID").ToString().Trim();
                NameTextEdit.Text = gridView1.GetFocusedRowCellValue("Name").ToString().Trim();
                NumberTextEdit.Text = gridView1.GetFocusedRowCellValue("Number").ToString().Trim();
                StartTimeTimeSpanEdit.Text = gridView1.GetFocusedRowCellValue("StartTime").ToString().Trim();
            }
            catch (Exception ex)
            {

            }
        }
    }
}
