using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;


namespace JTex.Forms.Accounts
{
    public partial class BankForm : Form
    {
        public BankForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard

        }


        private void ClearALL()
        {
            BankIDTextEdit.Text = "";
            AccountIDTextEdit.Text = "";
            AccountNumberTextEdit.Text = "";
            IBANNumberTextEdit.Text = "";
            AccountTitleTextEdit.Text = "";
            SwiftCodeTextEdit.Text = "";
            NameTextEdit.Text = "";
        }
        private void BankSelection()
        {
            
        }
        private void BankForm_Load(object sender, EventArgs e)
        {
            BankSelection();
        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
          
        }

        private void BtnUpdate_Click(object sender, EventArgs e)
        {
            
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
           
        }

        private void BtnClear_Click(object sender, EventArgs e)
        {
            ClearALL();
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            try
            {
                BankIDTextEdit.Text = gridView1.GetFocusedRowCellValue("BankID").ToString().Trim();
                AccountIDTextEdit.Text = gridView1.GetFocusedRowCellValue("AccountID").ToString().Trim();
                NameTextEdit.Text = gridView1.GetFocusedRowCellValue("Name").ToString().Trim();
                AccountNumberTextEdit.Text = gridView1.GetFocusedRowCellValue("AccountNumber").ToString().Trim();
                IBANNumberTextEdit.Text = gridView1.GetFocusedRowCellValue("IBANNumber").ToString().Trim();
                AccountTitleTextEdit.Text = gridView1.GetFocusedRowCellValue("AccountTitle").ToString().Trim();
                SwiftCodeTextEdit.Text = gridView1.GetFocusedRowCellValue("SwiftCode").ToString().Trim();
            }
            catch(Exception ex)
            {

            }
        }
    }
}
