using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;


namespace JTex.Forms.Accounts
{
    public partial class CustomersForm : Form
    {
        public CustomersForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
           
        }


        private void CustomerSelection()
        {
          
        }
        private void BtnAdd_Click(object sender, EventArgs e)
        {
            
            
        }

        private void BtnUpdate_Click(object sender, EventArgs e)
        {
            
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
        }

        private void CustomersForm_Load(object sender, EventArgs e)
        {
            CustomerSelection();
        }
    }
}
