using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Modelx;


namespace JTex.Forms.Accounts
{
    public partial class InvoicesForm : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public InvoicesForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Modelx.ADOEntityModel dbContext = new Modelx.ADOEntityModel();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.GL_Voucher_Item_Type.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gL_Voucher_Item_TypeBindingSource.DataSource = dbContext.GL_Voucher_Item_Type.Local.ToBindingList();
        }
        ADOEntityModel db;

      
        ADOEntityModel adOBj;
        private void GLEnteriesForm_Load(object sender, EventArgs e)
        {
            adOBj = new ADOEntityModel();
            adOBj.GL_Voucher_Item_Type.Load();
            gL_Voucher_Item_TypeBindingSource.DataSource = adOBj.GL_Voucher_Item_Type.Local;
        }
        GL_Voucher_Item_Type glObj = new GL_Voucher_Item_Type();
        private void bbiEdit_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            gL_Voucher_Item_TypeBindingSource.AddNew();
        }

        private void bbiNew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            adOBj.SaveChanges();
        }

        private void bbiRefresh_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            adOBj = new ADOEntityModel();
            adOBj.GL_Voucher_Item_Type.Load();
            gL_Voucher_Item_TypeBindingSource.DataSource = adOBj.GL_Voucher_Item_Type.Local;
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gL_Voucher_Item_TypeBindingSource.RemoveCurrent();
        }

        private void bbiPrintPreview_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }
    }
}
