using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Modelx;


namespace JTex.Forms
{
    public partial class DepartmentFrom : Form
    {
        public DepartmentFrom()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Modelx.ADOEntityModel dbContext = new Modelx.ADOEntityModel();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Departments.Load();
            // This line of code is generated by Data Source Configuration Wizard
            departmentsBindingSource.DataSource = dbContext.Departments.Local.ToBindingList();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
             dbContext = new Modelx.ADOEntityModel();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Units.Load();
            // This line of code is generated by Data Source Configuration Wizard
            unitsBindingSource.DataSource = dbContext.Units.Local.ToBindingList();
        }


        private void DepartmentFrom_Load(object sender, EventArgs e)
        {
            
        }
        ADOEntityModel DbContext = new ADOEntityModel();
        Department dObj = new Department();

        private bool Validation()
        {
            bool isSucess = false;
            if (UnitIDLookUpEdit.Text != "")
                if (NameTextEdit.Text != "")
                    if (AbbrevationTextEdit.Text != "")
                        isSucess = true;
                    else
                        isSucess = false;
            return isSucess;
        }
        private void popGrid()
        {
            DbContext = new Modelx.ADOEntityModel();
            DbContext.Departments.Load();
            gridControl1.DataSource = DbContext.Departments.Local;
        }


        private void bbiNew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if(Validation())
            {
                dObj.UnitID = Convert.ToInt32(UnitIDLookUpEdit.Text.Trim());
                dObj.Name = NameTextEdit.Text.Trim();
                dObj.Abbrevation = AbbrevationTextEdit.Text.Trim();

                using (var myDbEntities = new ADOEntityModel())
                {
                    myDbEntities.Departments.Add(dObj);
                    myDbEntities.SaveChanges();
                }
                popGrid();
            }
            else
            {
                MessageBox.Show("please fill data in fields...");
            }
        }

        private void bbiEdit_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if(DepartmentIDTextEdit.Text!="")
            {
                dObj.DepartmentID = Convert.ToInt32(DepartmentIDTextEdit.Text.Trim());
                dObj.UnitID = Convert.ToInt32(UnitIDLookUpEdit.Text.Trim());
                dObj.Name = NameTextEdit.Text.Trim();
                dObj.Abbrevation = AbbrevationTextEdit.Text.Trim();

                using (var myDbEntities = new ADOEntityModel())
                {
                    myDbEntities.Entry(dObj).State = EntityState.Modified;
                    myDbEntities.SaveChanges();
                }
                popGrid();
            }
            else
            {
                MessageBox.Show("Please enter department id...");
            }
        }

        private void bbiDelete_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (DepartmentIDTextEdit.Text != "")
            {
                dObj.DepartmentID = Convert.ToInt32(DepartmentIDTextEdit.Text.Trim());
                using (var myDbEntities = new ADOEntityModel())
                {
                    var entery = myDbEntities.Entry(dObj);
                    if (entery.State == System.Data.Entity.EntityState.Detached)
                    {
                        myDbEntities.Departments.Attach(dObj);
                        myDbEntities.Departments.Remove(dObj);
                        myDbEntities.SaveChanges();
                    }
                }
                popGrid();
            }
            else
            {
                MessageBox.Show("Please enter department id...");
            }
        }

        private void gridView1_FocusedRowChanged_1(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            try
            {
                DepartmentIDTextEdit.Text = gridView1.GetFocusedRowCellValue("DepartmentID").ToString().Trim();
                UnitIDLookUpEdit.Text = gridView1.GetFocusedRowCellValue("UnitID").ToString().Trim();
                NameTextEdit.Text = gridView1.GetFocusedRowCellValue("Name").ToString().Trim();
                AbbrevationTextEdit.Text = gridView1.GetFocusedRowCellValue("Abbrevation").ToString().Trim();
            }
            catch(Exception ex)
            {

            }
        }

        private void bbiPrintPreview_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridControl1.ShowRibbonPrintPreview();
        }
    }
}
