using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Modelx;
using System.Data.Entity;
using Modelx;


namespace JTex.Forms
{
    public partial class SubsectionForm : Form
    {
        public SubsectionForm()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Modelx.ADOEntityModel dbContext = new Modelx.ADOEntityModel();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Subsections.Load();
            // This line of code is generated by Data Source Configuration Wizard
            subsectionsBindingSource.DataSource = dbContext.Subsections.Local.ToBindingList();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            dbContext = new Modelx.ADOEntityModel();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Sections.Load();
            // This line of code is generated by Data Source Configuration Wizard
            sectionsBindingSource.DataSource = dbContext.Sections.Local.ToBindingList();
        }

        private void bbiPrintPreview_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridControl1.ShowRibbonPrintPreview();
        }
        ADOEntityModel DbContext = new ADOEntityModel();
        Subsection sObj = new Subsection();
        private bool Validation()
        {
            bool isSuccess = false;
            if (SectionIDLookUpEdit.Text != "")
                if (NumberTextEdit.Text != "")
                    if (NameTextEdit.Text != "")
                        if (AbbrevationTextEdit.Text != "")
                            isSuccess = true;
                        else
                            isSuccess = false;
            return isSuccess;
        }
        private void popGrid()
        {
            DbContext = new Modelx.ADOEntityModel();
            DbContext.Subsections.Load();
            gridControl1.DataSource = DbContext.Subsections.Local;
        }
        private void bbiNew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (Validation())
            {
                sObj.SectionID = Convert.ToInt32(SectionIDLookUpEdit.Text.Trim());
                sObj.Name = NameTextEdit.Text.Trim();
                sObj.Number = Convert.ToInt32(NumberTextEdit.Text.Trim());
                sObj.Abbrevation = AbbrevationTextEdit.Text.Trim();

                using (var dbEntities = new ADOEntityModel())
                {
                    dbEntities.Subsections.Add(sObj);
                    dbEntities.SaveChanges();
                }
                popGrid();
            }
        }

        private void bbiEdit_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (SubsectionIDTextEdit.Text != "")
            {
                sObj.SubsectionID= Convert.ToInt32(SubsectionIDTextEdit.Text.Trim());
                sObj.SectionID = Convert.ToInt32(SectionIDLookUpEdit.Text.Trim());
                sObj.Name = NameTextEdit.Text.Trim();
                sObj.Number = Convert.ToInt32(NumberTextEdit.Text.Trim());
                sObj.Abbrevation = AbbrevationTextEdit.Text.Trim();

                using (var myDbEntities = new ADOEntityModel())
                {
                    myDbEntities.Entry(sObj).State = EntityState.Modified;
                    myDbEntities.SaveChanges();
                }
                popGrid();
            }
            else
            {
                MessageBox.Show("Please enter section id...");
            }
        }

        private void bbiDelete_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (SubsectionIDTextEdit.Text != "")
            {
                sObj.SubsectionID = Convert.ToInt32(SubsectionIDTextEdit.Text.Trim());
                using (var myDbEntities = new ADOEntityModel())
                {
                    var entery = myDbEntities.Entry(sObj);
                    if (entery.State == System.Data.Entity.EntityState.Detached)
                    {
                        myDbEntities.Subsections.Attach(sObj);
                        myDbEntities.Subsections.Remove(sObj);
                        myDbEntities.SaveChanges();
                    }
                }
                popGrid();
            }
            else
            {
                MessageBox.Show("Please enter group id...");
            }
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            try
            {
                SectionIDLookUpEdit.Text = gridView1.GetFocusedRowCellValue("SectionID").ToString().Trim();
                SubsectionIDTextEdit.Text = gridView1.GetFocusedRowCellValue("DepartmentID").ToString().Trim();
                NumberTextEdit.Text = gridView1.GetFocusedRowCellValue("Number").ToString().Trim();
                NameTextEdit.Text = gridView1.GetFocusedRowCellValue("Name").ToString().Trim();
                AbbrevationTextEdit.Text = gridView1.GetFocusedRowCellValue("Abbrevation").ToString().Trim();
            }
            catch (Exception ex)
            {

            }
        }
    }
}
