using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;


namespace JTex.Forms
{
    public partial class UnitForm : Form
    {
        public UnitForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
        }

        private void UnitForm_Load(object sender, EventArgs e)
        {
           
        }


        private void clearALL()
        {
        }
        private void UnitSelection()
        {
           
        }
        private void BtnAdd_Click(object sender, EventArgs e)
        {
            
        }

        private void BtnUpdate_Click(object sender, EventArgs e)
        {
          
        }

        private void BtnClear_Click(object sender, EventArgs e)
        {
            clearALL();
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
            
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            //GroupIDTextEdit.Text = gridView1.GetFocusedRowCellValue("UnitID").ToString().Trim();
            //TBBranchID.Text = gridView1.GetFocusedRowCellValue("BranchID").ToString().Trim();
            //TBNumber.Text = gridView1.GetFocusedRowCellValue("Number").ToString().Trim();
            //TBName.Text = gridView1.GetFocusedRowCellValue("Name").ToString().Trim();
            //TBAbbrevation.Text = gridView1.GetFocusedRowCellValue("Abbrevation").ToString().Trim();
        }
    }
}
