using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;


namespace JTex.Forms.Inventory
{
    public partial class ProductUnitForm : Form
    {
        public ProductUnitForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //productUnitsTableAdapter1.Fill(productUnitsDataSet1.ProductUnits);
        }

        private void ProductUnitSelection()
        {

        }
        private void ProductUnitForm_Load(object sender, EventArgs e)
        {
            ProductUnitSelection();
        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
            
        }
    }
}
