using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;


namespace JTex.Forms.Inventory
{
    public partial class ProductsForm : Form
    {
        public ProductsForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
        }

        private void ProductsSelection()
        {
          
        }
        private void ProductsForm_Load(object sender, EventArgs e)
        {
            ProductsSelection();
        }
    }
}
